'use strict';
module.exports = app => {
  const { router, controller } = app;
  router.get('/', controller.admin.home);
  router.post('/mock/api/article/list', controller.admin.list);
  router.post('/mock/api/article/add', controller.admin.add);
  router.get('/mock/api/article/del/:id', controller.admin.del);
  router.get('/mock/api/article/:id', controller.admin.detail);
  router.post('/mock/api/url/swagger', controller.urlManage.swaggerUrlList);
  router.post('/mock/api/url/delete', controller.urlManage.delete);
  router.post('/mock/api/url/batch/delete', controller.urlManage.batchDelete);
  router.post('/mock/api/url/request/target/switch', controller.urlManage.requestTargetSwitch);
  router.get('/mock/api/url/list', controller.urlManage.list);
  router.post('/mock/api/url/mock/data', controller.urlResponseManage.mockData);
  router.get('/mock/api/url/response/list', controller.urlResponseManage.getUrlResponseList);
  router.post('/mock/api/url/response/edit', controller.urlResponseManage.editUrlResponse);
  router.get('/mock(/.+)?', controller.admin.home);
  router.get(/[a-z]+/, controller.urlForward.forwardGet);
  router.post(/[a-z]+/, controller.urlForward.forwardPost);
};