'use strict';
module.exports = app => {
  const { router, controller } = app;
  router.get('/', controller.admin.home);
  router.post('/mock/api/article/list', controller.admin.list);
  router.post('/mock/api/article/add', controller.admin.add);
  router.get('/mock/api/article/del/:id', controller.admin.del);
  router.get('/mock/api/article/:id', controller.admin.detail);
  router.post('/mock/api/url/swagger', controller.urlManage.swaggerUrlList);
  router.post('/mock/api/url/delete', controller.urlManage.delete);
  router.post('/mock/api/url/batch/delete', controller.urlManage.batchDelete);
  router.post('/mock/api/url/request/target/switch', controller.urlManage.requestTargetSwitch);
  router.get('/mock/api/url/list', controller.urlManage.list);
  router.post('/mock/api/url/mock/data', controller.urlResponseManage.mockData);
  router.get('/mock/api/url/response/list', controller.urlResponseManage.getUrlResponseList);
  router.get('/mock/api/url/response/by/params', controller.urlResponseManage.getUrlResponseByParams);
  router.post('/mock/api/url/response/edit', controller.urlResponseManage.editUrlResponse);
  router.get('/mock/api/system/list', controller.systemManage.list);
  router.post('/mock/api/system/add', controller.systemManage.add);
  router.post('/mock/api/system/delete', controller.systemManage.delete);
  router.post('/mock/api/system/enable', controller.systemManage.enableSwitch);
  router.get('/mock(/.+)?', controller.admin.notFound);
  router.get(/([a-z]+)/, controller.urlForward.forward);
  router.post(/([a-z]+)/, controller.urlForward.forward);
};